"""Output writers — currently just the radar.md archive file. Email digest lives in email_digest.py."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

log = logging.getLogger(__name__)


# ─── RADAR.MD ────────────────────────────────────────────────────────────────


def _md_section(title: str, items: list[dict]) -> str:
    """Render one tier section of radar.md."""
    if not items:
        return f"### {title}\n\n_No items in this tier._\n\n"

    out = [f"### {title}\n"]
    for it in items:
        projects = ", ".join(it.get("project_match", [])) or "—"
        out.append(
            f"- **[{it['title']}]({it['url']})** "
            f"`{it['score']}` · {it['source']} · {projects}  \n"
            f"  {it.get('claude_summary', '')}  \n"
            f"  _Why it matters:_ {it.get('why_it_matters', '')}\n"
        )
    return "\n".join(out) + "\n"


def write_radar_md(items: list[dict], output_path: Path) -> None:
    """Write the human-readable radar.md digest."""
    now = datetime.now(timezone.utc)
    act_now = [i for i in items if i["tier"] == "🔥 Act Now"]
    watch = [i for i in items if i["tier"] == "👀 Watch"]
    archive = [i for i in items if i["tier"] == "📦 Archive"]

    content = f"""# 📡 NoZak Labs — AI Radar

> _Last updated: {now.strftime("%Y-%m-%d %H:%M UTC")}_
> _Total items this run: {len(items)} \
({len(act_now)} act now, {len(watch)} watch, {len(archive)} archive)_

Review during your Sunday 1:30 PM Cairo slot. \
Full archive available in [radar.md](https://github.com/NohaZak/ai-radar-agent/blob/main/radar.md).

---

## 🔥 Act Now ({len(act_now)})

_High-relevance items — evaluate during your radar slot._

{_md_section("", act_now)}

---

## 👀 Watch ({len(watch)})

_Tangential relevance — skim if time permits._

{_md_section("", watch)}

---

## 📦 Archive ({len(archive)})

_Low-relevance — kept for searchability only._

{_md_section("", archive)}

---

_Generated by the [AI Radar Agent](https://github.com/NohaZak/ai-radar-agent)._
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    log.info(f"Wrote radar.md ({len(items)} items) to {output_path}")
